using SoftLiu.Event;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class App : AutoGeneratedSingletonMonobehaviour<App>
{
    private bool m_init = false;

    private void Awake()
    {

    }

    public void Init()
    {
        if (m_init) return;
        m_init = true;
    }

    private bool m_currentPause = false;
    public bool currentPause
    {
        get { return m_currentPause; }
        set
        {
            if (m_currentPause != value)
            {
                m_currentPause = value;
                EventManager<Events>.Instance.TriggerEvent(Events.GamePause, m_currentPause);
            }
        }
    }

    private bool m_inGame = false;
    public bool inGame
    {
        get { return m_inGame; }
        set { m_inGame = value; }
    }

    private Player m_activePlayer = null;
    public void SetActivePlayer(Player player)
    {
        m_activePlayer = player;
    }

    public Player GetActivePlayer()
    {
        return m_activePlayer;
    }
}
