using SoftLiu.Save;
using SoftLiu.Utilities;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace SoftLiu.Authentication
{
    public class Authenticator : AutoGeneratedSingleton<Authenticator>
    {
        private DeviceToken m_deviceToken = null;
        public DeviceToken deviceToken
        {
            get { return m_deviceToken; }
        }
        private User m_user = null;
        public User User
        {
            get { return m_user; }
            set { m_user = value; }
        }

        public Authenticator()
        {
            m_deviceToken = new DeviceToken();
            if (m_user == null)
            {
                m_user = new User();
                m_user.Load();
            }
        }
    }
}
