using SoftLiu.Utilities;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MissionManager : AutoGeneratedSingletonMonobehaviour<MissionManager>
{

    public void Init()
    {
        
    }

}
