using SoftLiu.Utilities;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameDataManager : AutoGeneratedSingleton<GameDataManager>
{
    public const string GameDBPath = "GameDB/gameDB";
    public const string GameDBJsonPath = "Assets/Misc/GameDB/gameDB.json";
    public const string cachedEventData = "CachedEventData";

    public const string dateTimeFormat = "dd/MM/yyyy HH:mm:ss";
    private const int CheckSumLength = 128;

    private GameDB m_db = null;
    private string m_previousCachedChecksum = null;


    public GameDB gameDB
    {
        get { return m_db; }
    }
}
